package actiontype

const (
	PRICE  = "PRICE"
	TRADES = "TRADES" // Trades - only requires the actionType parameter
)

var ACTIONS = []string{
	"ORDER_TYPE_BUY",
	"ORDER_TYPE_SELL",
	"ORDER_TYPE_BUY_LIMIT",
	"ORDER_TYPE_SELL_LIMIT",
	"ORDER_TYPE_BUY_STOP_LIMIT",
	"ORDER_TYPE_SELL_STOP_LIMIT",
	"ORDER_TYPE_CLOSE_BY",
	"ORDER_CANCEL",
	"POSITION_CLOSE_ID",
	"POSITION_CLOSE_SYMBOL",
	"POSITION_PARTIAL",
}
